//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveMe.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ride
    {
        public int Id { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public System.DateTime Datetime { get; set; }
        public Nullable<int> RideType { get; set; }
        public Nullable<int> RideMode { get; set; }
        public Nullable<int> UserId { get; set; }
        public int NumberOfPersons { get; set; }
    
        public virtual RideMode RideMode1 { get; set; }
        public virtual RideType RideType1 { get; set; }
        public virtual User User { get; set; }
    }
}
